name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    
    - run: go get -u golang.org/x/lint/golint
    - run: go mod vendor
    - run: golint -set_exit_status .
    - run: go vet .
    - run: go build
    - run: ls -al

  docker:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: env
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: docker build and push
        run: |
          make REGISTRY="localhost:5000" VERSION="${GITHUB_SHA}" all
          make REGISTRY="localhost:5000" VERSION="${GITHUB_SHA}" push
          make REGISTRY="localhost:5000" VERSION="${GITHUB_SHA}" push-short
          make REGISTRY="localhost:5000" VERSION="${GITHUB_SHA}" push-latest
      - run: docker images
      
