name: docker

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+.[0-9]

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get branch name
        uses: nelonoel/branch-name@v1.0.1
      - name: Print branch name
        run: echo ${BRANCH_NAME}
      - run: env
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      #- name: Login to DockerHub
      #  uses: docker/login-action@v1
      #  with:
      #    username: ${{ secrets.DOCKERHUB_USERNAME }}
      #    password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: docker build and push
        run: |
          make VERSION="${BRANCH_NAME}" all
          docker images
          make VERSION="${BRANCH_NAME}" push
          make VERSION="${BRANCH_NAME}" push-short
          make VERSION="${BRANCH_NAME}" push-latest
